import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import {WebsiteHeader} from "~/app/_components/WebsiteHeader";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

    return (
      <html lang="en" className="h-full bg-white">
      <head>

      </head>

      <body className={`font-sans ${inter.variable} h-full`}>
      <TRPCReactProvider cookies={cookies().toString()}>
        <WebsiteHeader />
          {children}
      </TRPCReactProvider>
      </body>
      </html>
  );
}